name: Deploy ProjectDemo.Api to Azure Web App (via Service Principal)

on:
  push:
    branches:
      - master
    paths:
      - "ProjectDemo.Api/**"
      - ".github/workflows/deploy-projectdemo-api.yml"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_API_CREDENTIALS }}

      - name: Publish .NET app
        run: |
          dotnet restore ./ProjectDemo.Api/ProjectDemoApi.csproj
          dotnet build ./ProjectDemo.Api/ProjectDemoApi.csproj --configuration Release --no-restore
          dotnet publish ./ProjectDemo.Api/ProjectDemoApi.csproj --configuration Release --output ./publish

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ProjectDemoApi
          package: ./publish
