name: Deploy ProjectDemo.Api to Azure Web App

on:
  push:
    branches:
      - master
    paths:
      - "ProjectDemo.Api/**"
      - ".github/workflows/deploy-projectdemo-api.yml"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x" # Or your target version

      - name: Restore dependencies
        run: dotnet restore ./ProjectDemo.Api/ProjectDemo.Api.csproj

      - name: Build
        run: dotnet build ./ProjectDemo.Api/ProjectDemo.Api.csproj --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ./ProjectDemo.Api/ProjectDemo.Api.csproj --configuration Release --output ./publish

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: <your-azure-webapp-name>
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./publish
