name: Export Azure Resources to Azure Containers
on:
  schedule:
    - cron: "0 1 * * *" # Every night at 1 AM
  workflow_dispatch:

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_STORAGE_CREDENTIALS }}

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Install aztfexport
        run: |
          go install github.com/Azure/aztfexport@latest
          echo "${HOME}/go/bin" >> $GITHUB_PATH

      #   - name: Clean output directory
      #     run: rm -rf ./terraform/dev && mkdir -p ./terraform/dev
      - name: Export Resource Group
        run: |
          aztfexport rg --output-dir ./terraform/dev --append --non-interactive RG-ProjectDemo-Dev
        #   git config user.name "github-actions"
        #   git config user.email "github-actions@github.com"
        #   git add .
        #   git commit -m "Nightly export of dev resources" || echo "No changes"
        #   git push
